# -*- coding: utf-8 -*-
"""OpenAI Whisper from Hugging Face Transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3uNwqxl3r3UpMhCUwAMo3zXZtOETaT2
"""

!nvidia-smi

! pip install git+https://github.com/huggingface/transformers -q

!wget -O audio.mp3 http://www.moviesoundclips.net/movies1/darkknight/criminal.mp3

from IPython.display import Audio, display

display(Audio('audio.mp3', autoplay=True))

from transformers import pipeline

whisper = pipeline('automatic-speech-recognition', model = 'openai/whisper-medium', device = 0)

text = whisper('audio.mp3')

text

